---
title: "Lab5"
author: "Aksel Can Sozudogru"
date: "2024-06-23"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Task 1

```{r}
getwd()
```

## Task 2

```{r}
chisim <- function(n1 = 10, sigma1 = 3, mean1 = 5, iter = 1000, ...) {
  y1 = rnorm(n1*iter, mean = mean1, sd = sigma1) # generate iter samples of size n1
  data1.mat = matrix(y1, nrow = n1, ncol = iter, byrow = TRUE)
  # Each column is a sample size n1
  ssq1 = apply(data1.mat, 2, var) # ssq1 is s squared
  w = (n1 - 1) * ssq1/sigma1^2 # chi-sq stat
  summary = hist(w, plot = F)
  ymax = 1.2 * max(summary$density)
  hist(w, freq = FALSE, ylim = c(0, ymax), main = substitute(paste("Sample size = ", n[1], " = ", n1, ", statistic = ", chi^2)),
       xlab = expression(paste(chi^2, "Statistic", sep = "")), las = 1)
  lines(density(w), col = "Blue", lwd = 3) # add a density plot
  curve(dchisq(x, n1 - 1), add = TRUE, col = "Red", lty = 2, lwd = 3) # add a theoretical curve
  title = expression(paste(chi^2 == frac((n[1] - 1) * s^2, sigma^2))) # mathematical annotation - see plotmath
  legend("topright", 
         legend = c("Simulated", "Theoretical"), 
         col = c("Blue", "Red"), lwd = 4, lty = 1:2, bty = "n", 
         title = title) # Legend
  return(list(w = w, summary = summary(w), sd = sd(w), fun = "Chi-sq")) # some output to use if needed
}


for (n in c(10, 20, 100, 200)) {
  chisim(n1 = n, iter = 1000, mean1 = 10, sigma1 = 4);
}
```



## Task 3

```{r}
tsim <- function(n1 = 10, sigma1 = 3, mean1 = 5, iter = 1000, ...) {
  y1 = rnorm(n1 * iter, mean = mean1, sd = sigma1) # generate iter samples of size n1
  data1.mat = matrix(y1, nrow = n1, ncol = iter, byrow = TRUE)
  # Each column is a sample size n1
  s = apply(data1.mat, 2, sd)
  m = apply(data1.mat, 2, mean)
  w = (m - mean1) * sqrt(n1) / s # t
  summary = hist(w, plot = F)
  ymax = 1.2 * max(summary$density)
  hist(w, freq = FALSE, ylim = c(0, ymax), main = substitute(paste("Sample size = ", n[1], " = ", n1, ", statistic = ", t)),
       xlab = expression(paste(t, "Statistic", sep = "")), las = 1)
  lines(density(w), col = "Blue", lwd = 3) # add a density plot
  curve(dt(x, n1 - 1), add = TRUE, col = "Red", lty = 2, lwd = 3) # add a theoretical curve
  title = expression(paste(t == frac(bar(y) - mu, frac(s, sqrt(n)))))
  legend(x = 0.7 * (max(summary$breaks) - min(summary$breaks)) + min(summary$breaks), y = 0.95 * ymax, 
         c("Simulated", "Theoretical"), col = c("Blue", "Red"), lwd = 4, lty = 1:2, bty = "n", title = title) # Legend
  return(list(w = w, summary = summary(w), sd = sd(w), fun = "t")) # some output to use if needed
}

for (n in c(10, 20, 100, 200)) {
  tsim(n1 = n, iter = 1000, mean1 = 10, sigma1 = 4);
} 
```



## Task 4


```{r}

chisim2 <- function(n1 = 10, n2 = 14, sigma1 = 3, sigma2 = 3, mean1 = 5, mean2 = 10, iter = 1000, ...) {
  y1 = rnorm(n1*iter, mean = mean1, sd = sigma1) # generate iter samples of size n1
  y2 = rnorm(n2*iter, mean = mean2, sd = sigma2) # generate iter samples of size n2
  data1.mat = matrix(y1, nrow = n1, ncol = iter, byrow = TRUE)
  data2.mat = matrix(y2, nrow = n2, ncol = iter, byrow = TRUE)
  # Each column is a sample size n1
  ssq1 = apply(data1.mat, 2, var) # ssq1 is s squared
  ssq2 = apply(data2.mat, 2, var) # ssq2 is s squared
  spsq = ((n1 - 1)*ssq1 + (n2 - 1)*ssq2)/(n1 + n2 - 2) # pooled s squared
  w = (n1 + n2 - 2)*spsq/(sigma1^2) # sigma1=sigma2, Chi square stat
  summary <- hist(w, plot = F)
  ymax = 1.2 * max(summary$density)
  hist(w, freq = FALSE, ylim = c(0, ymax), # Histogram with annotation
       main = substitute(paste("Sample size = ", n[1], " = ", n1, ", ", n[2], " = ", n2, ", statistic = ", chi^2)),
       xlab = expression(paste(chi^2, "Statistic", sep = "")), las = 1)
  lines(density(w), col = "Blue", lwd = 3) # add a density plot
  curve(dchisq(x, n1 + n2 - 2), add = TRUE, col = "Red", lty = 2, lwd = 3) # add a theoretical curve
  title = expression(chi^2 == frac((n[1] + n[2] - 2)*S[p]^2, sigma^2)) # mathematical annotation - see plotmath
  legend(x = 0.75 * (max(summary$breaks) - min(summary$breaks)) + min(summary$breaks), y = 0.95 * ymax, 
         c("Simulated", "Theoretical"), col = c("Blue", "Red"), lwd = 4, lty = 1:2, bty = "n", title = title) # Legend
  return(list(w = w, summary = summary(w), sd = sd(w), fun = "Chi-sq")) # some output to use if needed
}

. = chisim2(n1 = 10, n2 = 10, mean1 = 5, mean2 = 10, sigma1 = 4, sigma2 = 4, iter = 1000);

```

```{r}
. = chisim2(n1 = 20, n2 = 10, mean1 = 3, mean2 = 5, sigma1 = 10, sigma2 = 10, iter = 1000);

```


```{r}
. = chisim2(n1 = 50, n2 = 50, mean1 = 5, mean2 = 10, sigma1 = 4, sigma2 = 4, iter = 10000);

```

```{r}
. = chisim2(n1 = 80, n2 = 50, mean1 = 3, mean2 = 5, sigma1 = 10, sigma2 = 10, iter = 10000);

```

## Task 5


```{r}
tsim2 <- function(n1 = 10, n2 = 14, sigma1 = 3, sigma2 = 3, mean1 = 5, mean2 = 10, iter = 1000, ymax = 0.5, ...) {
  y1 = rnorm(n1 * iter, mean = mean1, sd = sigma1) # generate iter samples of size n1
  y2 = rnorm(n2 * iter, mean = mean2, sd = sigma2) # generate iter samples of size n2
  data1.mat = matrix(y1, nrow = n1, ncol = iter, byrow = TRUE)
  data2.mat = matrix(y2, nrow = n2, ncol = iter, byrow = TRUE)
  # Each column is a sample size n1
  ssq1 = apply(data1.mat, 2, var) # ssq1 is s squared
  ybar1 = apply(data1.mat, 2, mean)
  ssq2 = apply(data2.mat, 2, var)
  ybar2 = apply(data2.mat, 2, mean)
  spsq = ((n1 - 1) * ssq1 + (n2 - 1) * ssq2) / (n1 + n2 - 2) # pooled s squared
  w = ((ybar1 - ybar2) - (mean1 - mean2)) / sqrt(spsq * (1/n1 + 1/n2)) # sigma1 = sigma2, Chi square stat
  summary = hist(w, plot = F)
  ymax = 1.2 * max(summary$density)
  hist(w, freq = FALSE, ylim = c(0, ymax), # Histogram with annotation
       main = substitute(paste("Sample size = ", n[1] + n[2], " = ", n1 + n2, ", statistic = ", T)),
       xlab = expression(paste(T, " Statistic", sep = "")), las = 1)
  lines(density(w), col = "Blue", lwd = 3) # add a density plot
  curve(dt(x, n1 + n2 - 2), add = TRUE, col = "Red", lty = 2, lwd = 3) # add a theoretical curve
  title = expression(paste(T == frac((bar(Y)[1] - bar(Y)[2]) - (mu[1] - mu[2]), sqrt(frac(1, n[1]) + frac(1, n[2]))))) # mathematical annotation - see plotmath
  legend(x = 0.7 * (max(summary$breaks) - min(summary$breaks)) + min(summary$breaks), y = 0.8 * ymax, 
         c("Simulated", "Theoretical"), col = c("Blue", "Red"), lwd = 4, lty = 1:2, bty = "n", title = title) # Legend
  return(list(w = w, summary = summary(w), sd = sd(w), fun = "T")) # some output to use if needed
}

```


```{r}
. = tsim2(n1 = 10, n2 = 10, mean1 = 5, mean2 = 10, sd1 = 4, sd2 = 4, iter = 1000);

```


```{r}
. = tsim2(n1 = 20, n2 = 10, mean1 = 3, mean2 = 5, sd1 = 10, sd2 = 10, iter = 1000);

```

```{r}
. = tsim2(n1 = 50, n2 = 50, mean1 = 5, mean2 = 10, sd1 = 4, sd2 = 4, iter = 10000);

```


```{r}
. = tsim2(n1 = 80, n2 = 50, mean1 = 3, mean2 = 5, sd1 = 10, sd2 = 10, iter = 10000);

```



## Task 6

```{r}
fsim2 <- function(n1 = 10, n2 = 14, sigma1 = 3, sigma2 = 2, mean1 = 5, mean2 = 10, iter = 1000, ...) {
  y1 = rnorm(n1 * iter, mean = mean1, sd = sigma1) # generate iter samples of size n1
  y2 = rnorm(n2 * iter, mean = mean2, sd = sigma2) # generate iter samples of size n2
  data1.mat = matrix(y1, nrow = n1, ncol = iter, byrow = TRUE)
  data2.mat = matrix(y2, nrow = n2, ncol = iter, byrow = TRUE)
  # Each column is a sample size n1
  ssq1 = apply(data1.mat, 2, var) # ssq1 is s squared
  ssq2 = apply(data2.mat, 2, var)
  w = ssq1 * sigma2^2 / (ssq2 * sigma1^2) # pooled s squared
  summary = hist(w, plot = F)
  ymax = 1.4 * max(summary$density)
  hist(w, freq = FALSE, ylim = c(0, ymax), # Histogram with annotation
       main = substitute(paste("Sample size = ", n[1], " + ", n[2], " = ", n1 + n2, ", statistic = ", F)),
       xlab = expression(paste(F, " Statistic", sep = "")), las = 1)
  lines(density(w), col = "Blue", lwd = 3) # add a density plot
  curve(df(x, n1 - 1, n2 - 1), xlim = c(0, 6), add = TRUE, col = "Red", lty = 2, lwd = 3) # add a theoretical curve
  title = expression(paste(F == frac((s[1]^2 * s[2]^2), frac(sigma[2]^2, sigma[1]^2)))) # mathematical annotation - see plotmath
  legend(x = 0.65 * (max(summary$breaks) - min(summary$breaks)) + min(summary$breaks), y = 0.9 * ymax, 
         c("Simulated", "Theoretical"), col = c("Blue", "Red"), lwd = 4, lty = 1:2, bty = "n", title = title) # Legend
  return(list(w = w, summary = summary(w), sd = sd(w), fun = "F")) # some output to use if needed
}

```



```{r}
. = fsim2(n1 = 100, n2 = 100, sigma1 = 1, sigma2 = 1, mean1 = 0, mean2 = 0, iter = 1000);

```


```{r}
. = fsim2(n1 = 200, n2 = 200, sigma1 = 1, sigma2 = 1, mean1 = 3, mean2 = 3, iter = 10000);

```



```{r}
. = fsim2(n1 = 1000, n2 = 100, sigma1 = 1, sigma2 = 1, mean1 = 5, mean2 = 5, iter = 1000);

```

```{r}
. = fsim2(n1 = 2000, n2 = 2000, sigma1 = 3, sigma2 = 3, mean1 = 5, mean2 = 5, iter = 10000);

```

